// Code generated by MockGen. DO NOT EDIT.
// Source: ../contracts.go
//
// Generated by this command:
//
//	mockgen -source=../contracts.go -destination=contracts_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	contracts "mosaic.local/mosaic/internal/contracts"
	gen "mosaic.local/mosaic/internal/ontology/gen"
)

// MockRawEventRepository is a mock of RawEventRepository interface.
type MockRawEventRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRawEventRepositoryMockRecorder
	isgomock struct{}
}

// MockRawEventRepositoryMockRecorder is the mock recorder for MockRawEventRepository.
type MockRawEventRepositoryMockRecorder struct {
	mock *MockRawEventRepository
}

// NewMockRawEventRepository creates a new mock instance.
func NewMockRawEventRepository(ctrl *gomock.Controller) *MockRawEventRepository {
	mock := &MockRawEventRepository{ctrl: ctrl}
	mock.recorder = &MockRawEventRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRawEventRepository) EXPECT() *MockRawEventRepositoryMockRecorder {
	return m.recorder
}

// AppendRawEvent mocks base method.
func (m *MockRawEventRepository) AppendRawEvent(arg0 context.Context, arg1 gen.RawEvent) (contracts.RawEventAppendResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendRawEvent", arg0, arg1)
	ret0, _ := ret[0].(contracts.RawEventAppendResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AppendRawEvent indicates an expected call of AppendRawEvent.
func (mr *MockRawEventRepositoryMockRecorder) AppendRawEvent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendRawEvent", reflect.TypeOf((*MockRawEventRepository)(nil).AppendRawEvent), arg0, arg1)
}

// FindRawEvent mocks base method.
func (m *MockRawEventRepository) FindRawEvent(ctx context.Context, rawEventID string) (gen.RawEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRawEvent", ctx, rawEventID)
	ret0, _ := ret[0].(gen.RawEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRawEvent indicates an expected call of FindRawEvent.
func (mr *MockRawEventRepositoryMockRecorder) FindRawEvent(ctx, rawEventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRawEvent", reflect.TypeOf((*MockRawEventRepository)(nil).FindRawEvent), ctx, rawEventID)
}

// MockCanonicalEventRepository is a mock of CanonicalEventRepository interface.
type MockCanonicalEventRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCanonicalEventRepositoryMockRecorder
	isgomock struct{}
}

// MockCanonicalEventRepositoryMockRecorder is the mock recorder for MockCanonicalEventRepository.
type MockCanonicalEventRepositoryMockRecorder struct {
	mock *MockCanonicalEventRepository
}

// NewMockCanonicalEventRepository creates a new mock instance.
func NewMockCanonicalEventRepository(ctrl *gomock.Controller) *MockCanonicalEventRepository {
	mock := &MockCanonicalEventRepository{ctrl: ctrl}
	mock.recorder = &MockCanonicalEventRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCanonicalEventRepository) EXPECT() *MockCanonicalEventRepositoryMockRecorder {
	return m.recorder
}

// AppendCanonicalEvent mocks base method.
func (m *MockCanonicalEventRepository) AppendCanonicalEvent(arg0 context.Context, arg1 gen.CanonicalEvent) (gen.CanonicalEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendCanonicalEvent", arg0, arg1)
	ret0, _ := ret[0].(gen.CanonicalEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AppendCanonicalEvent indicates an expected call of AppendCanonicalEvent.
func (mr *MockCanonicalEventRepositoryMockRecorder) AppendCanonicalEvent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendCanonicalEvent", reflect.TypeOf((*MockCanonicalEventRepository)(nil).AppendCanonicalEvent), arg0, arg1)
}

// ListCanonicalEventsAfter mocks base method.
func (m *MockCanonicalEventRepository) ListCanonicalEventsAfter(ctx context.Context, canonicalSeq int64) ([]gen.CanonicalEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCanonicalEventsAfter", ctx, canonicalSeq)
	ret0, _ := ret[0].([]gen.CanonicalEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCanonicalEventsAfter indicates an expected call of ListCanonicalEventsAfter.
func (mr *MockCanonicalEventRepositoryMockRecorder) ListCanonicalEventsAfter(ctx, canonicalSeq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCanonicalEventsAfter", reflect.TypeOf((*MockCanonicalEventRepository)(nil).ListCanonicalEventsAfter), ctx, canonicalSeq)
}

// ListEffectiveCanonicalEventsForIncident mocks base method.
func (m *MockCanonicalEventRepository) ListEffectiveCanonicalEventsForIncident(ctx context.Context, incidentID string) ([]gen.CanonicalEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEffectiveCanonicalEventsForIncident", ctx, incidentID)
	ret0, _ := ret[0].([]gen.CanonicalEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEffectiveCanonicalEventsForIncident indicates an expected call of ListEffectiveCanonicalEventsForIncident.
func (mr *MockCanonicalEventRepositoryMockRecorder) ListEffectiveCanonicalEventsForIncident(ctx, incidentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEffectiveCanonicalEventsForIncident", reflect.TypeOf((*MockCanonicalEventRepository)(nil).ListEffectiveCanonicalEventsForIncident), ctx, incidentID)
}

// MarkCanonicalEventProjected mocks base method.
func (m *MockCanonicalEventRepository) MarkCanonicalEventProjected(ctx context.Context, canonicalEventID string, stateRevision int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkCanonicalEventProjected", ctx, canonicalEventID, stateRevision)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkCanonicalEventProjected indicates an expected call of MarkCanonicalEventProjected.
func (mr *MockCanonicalEventRepositoryMockRecorder) MarkCanonicalEventProjected(ctx, canonicalEventID, stateRevision any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkCanonicalEventProjected", reflect.TypeOf((*MockCanonicalEventRepository)(nil).MarkCanonicalEventProjected), ctx, canonicalEventID, stateRevision)
}

// MockImmutableRecordRepository is a mock of ImmutableRecordRepository interface.
type MockImmutableRecordRepository struct {
	ctrl     *gomock.Controller
	recorder *MockImmutableRecordRepositoryMockRecorder
	isgomock struct{}
}

// MockImmutableRecordRepositoryMockRecorder is the mock recorder for MockImmutableRecordRepository.
type MockImmutableRecordRepositoryMockRecorder struct {
	mock *MockImmutableRecordRepository
}

// NewMockImmutableRecordRepository creates a new mock instance.
func NewMockImmutableRecordRepository(ctrl *gomock.Controller) *MockImmutableRecordRepository {
	mock := &MockImmutableRecordRepository{ctrl: ctrl}
	mock.recorder = &MockImmutableRecordRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImmutableRecordRepository) EXPECT() *MockImmutableRecordRepositoryMockRecorder {
	return m.recorder
}

// AppendAuditRecord mocks base method.
func (m *MockImmutableRecordRepository) AppendAuditRecord(arg0 context.Context, arg1 gen.AuditRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendAuditRecord", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendAuditRecord indicates an expected call of AppendAuditRecord.
func (mr *MockImmutableRecordRepositoryMockRecorder) AppendAuditRecord(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendAuditRecord", reflect.TypeOf((*MockImmutableRecordRepository)(nil).AppendAuditRecord), arg0, arg1)
}

// AppendInsight mocks base method.
func (m *MockImmutableRecordRepository) AppendInsight(arg0 context.Context, arg1 gen.Insight) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendInsight", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendInsight indicates an expected call of AppendInsight.
func (mr *MockImmutableRecordRepositoryMockRecorder) AppendInsight(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendInsight", reflect.TypeOf((*MockImmutableRecordRepository)(nil).AppendInsight), arg0, arg1)
}

// AppendLunaResult mocks base method.
func (m *MockImmutableRecordRepository) AppendLunaResult(arg0 context.Context, arg1 gen.LunaResult) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendLunaResult", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendLunaResult indicates an expected call of AppendLunaResult.
func (mr *MockImmutableRecordRepositoryMockRecorder) AppendLunaResult(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendLunaResult", reflect.TypeOf((*MockImmutableRecordRepository)(nil).AppendLunaResult), arg0, arg1)
}

// AppendModelRun mocks base method.
func (m *MockImmutableRecordRepository) AppendModelRun(arg0 context.Context, arg1 gen.ModelRun) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendModelRun", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendModelRun indicates an expected call of AppendModelRun.
func (mr *MockImmutableRecordRepositoryMockRecorder) AppendModelRun(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendModelRun", reflect.TypeOf((*MockImmutableRecordRepository)(nil).AppendModelRun), arg0, arg1)
}

// AppendRecommendation mocks base method.
func (m *MockImmutableRecordRepository) AppendRecommendation(arg0 context.Context, arg1 gen.Recommendation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendRecommendation", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendRecommendation indicates an expected call of AppendRecommendation.
func (mr *MockImmutableRecordRepositoryMockRecorder) AppendRecommendation(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendRecommendation", reflect.TypeOf((*MockImmutableRecordRepository)(nil).AppendRecommendation), arg0, arg1)
}

// MockAdvisoryHistoryReader is a mock of AdvisoryHistoryReader interface.
type MockAdvisoryHistoryReader struct {
	ctrl     *gomock.Controller
	recorder *MockAdvisoryHistoryReaderMockRecorder
	isgomock struct{}
}

// MockAdvisoryHistoryReaderMockRecorder is the mock recorder for MockAdvisoryHistoryReader.
type MockAdvisoryHistoryReaderMockRecorder struct {
	mock *MockAdvisoryHistoryReader
}

// NewMockAdvisoryHistoryReader creates a new mock instance.
func NewMockAdvisoryHistoryReader(ctrl *gomock.Controller) *MockAdvisoryHistoryReader {
	mock := &MockAdvisoryHistoryReader{ctrl: ctrl}
	mock.recorder = &MockAdvisoryHistoryReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdvisoryHistoryReader) EXPECT() *MockAdvisoryHistoryReaderMockRecorder {
	return m.recorder
}

// ReadAdvisoryHistory mocks base method.
func (m *MockAdvisoryHistoryReader) ReadAdvisoryHistory(arg0 context.Context) (contracts.AdvisoryHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAdvisoryHistory", arg0)
	ret0, _ := ret[0].(contracts.AdvisoryHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAdvisoryHistory indicates an expected call of ReadAdvisoryHistory.
func (mr *MockAdvisoryHistoryReaderMockRecorder) ReadAdvisoryHistory(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAdvisoryHistory", reflect.TypeOf((*MockAdvisoryHistoryReader)(nil).ReadAdvisoryHistory), arg0)
}

// MockCheckpointRepository is a mock of CheckpointRepository interface.
type MockCheckpointRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCheckpointRepositoryMockRecorder
	isgomock struct{}
}

// MockCheckpointRepositoryMockRecorder is the mock recorder for MockCheckpointRepository.
type MockCheckpointRepositoryMockRecorder struct {
	mock *MockCheckpointRepository
}

// NewMockCheckpointRepository creates a new mock instance.
func NewMockCheckpointRepository(ctrl *gomock.Controller) *MockCheckpointRepository {
	mock := &MockCheckpointRepository{ctrl: ctrl}
	mock.recorder = &MockCheckpointRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCheckpointRepository) EXPECT() *MockCheckpointRepositoryMockRecorder {
	return m.recorder
}

// AppendCheckpoint mocks base method.
func (m *MockCheckpointRepository) AppendCheckpoint(arg0 context.Context, arg1 gen.Checkpoint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendCheckpoint", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendCheckpoint indicates an expected call of AppendCheckpoint.
func (mr *MockCheckpointRepositoryMockRecorder) AppendCheckpoint(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendCheckpoint", reflect.TypeOf((*MockCheckpointRepository)(nil).AppendCheckpoint), arg0, arg1)
}

// LatestCheckpoint mocks base method.
func (m *MockCheckpointRepository) LatestCheckpoint(arg0 context.Context) (gen.Checkpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LatestCheckpoint", arg0)
	ret0, _ := ret[0].(gen.Checkpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LatestCheckpoint indicates an expected call of LatestCheckpoint.
func (mr *MockCheckpointRepositoryMockRecorder) LatestCheckpoint(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LatestCheckpoint", reflect.TypeOf((*MockCheckpointRepository)(nil).LatestCheckpoint), arg0)
}

// MockTransactionRunner is a mock of TransactionRunner interface.
type MockTransactionRunner struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionRunnerMockRecorder
	isgomock struct{}
}

// MockTransactionRunnerMockRecorder is the mock recorder for MockTransactionRunner.
type MockTransactionRunnerMockRecorder struct {
	mock *MockTransactionRunner
}

// NewMockTransactionRunner creates a new mock instance.
func NewMockTransactionRunner(ctrl *gomock.Controller) *MockTransactionRunner {
	mock := &MockTransactionRunner{ctrl: ctrl}
	mock.recorder = &MockTransactionRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionRunner) EXPECT() *MockTransactionRunnerMockRecorder {
	return m.recorder
}

// WithinTransaction mocks base method.
func (m *MockTransactionRunner) WithinTransaction(arg0 context.Context, arg1 func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithinTransaction", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithinTransaction indicates an expected call of WithinTransaction.
func (mr *MockTransactionRunnerMockRecorder) WithinTransaction(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithinTransaction", reflect.TypeOf((*MockTransactionRunner)(nil).WithinTransaction), arg0, arg1)
}

// MockProjector is a mock of Projector interface.
type MockProjector struct {
	ctrl     *gomock.Controller
	recorder *MockProjectorMockRecorder
	isgomock struct{}
}

// MockProjectorMockRecorder is the mock recorder for MockProjector.
type MockProjectorMockRecorder struct {
	mock *MockProjector
}

// NewMockProjector creates a new mock instance.
func NewMockProjector(ctrl *gomock.Controller) *MockProjector {
	mock := &MockProjector{ctrl: ctrl}
	mock.recorder = &MockProjectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjector) EXPECT() *MockProjectorMockRecorder {
	return m.recorder
}

// ApplyCanonicalEvent mocks base method.
func (m *MockProjector) ApplyCanonicalEvent(arg0 context.Context, arg1 gen.CanonicalEvent) (contracts.ProjectionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyCanonicalEvent", arg0, arg1)
	ret0, _ := ret[0].(contracts.ProjectionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplyCanonicalEvent indicates an expected call of ApplyCanonicalEvent.
func (mr *MockProjectorMockRecorder) ApplyCanonicalEvent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyCanonicalEvent", reflect.TypeOf((*MockProjector)(nil).ApplyCanonicalEvent), arg0, arg1)
}

// Replay mocks base method.
func (m *MockProjector) Replay(arg0 context.Context, arg1 gen.Checkpoint, arg2 []gen.CanonicalEvent) (contracts.ProjectionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Replay", arg0, arg1, arg2)
	ret0, _ := ret[0].(contracts.ProjectionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Replay indicates an expected call of Replay.
func (mr *MockProjectorMockRecorder) Replay(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Replay", reflect.TypeOf((*MockProjector)(nil).Replay), arg0, arg1, arg2)
}

// MockCOPReadModelRepository is a mock of COPReadModelRepository interface.
type MockCOPReadModelRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCOPReadModelRepositoryMockRecorder
	isgomock struct{}
}

// MockCOPReadModelRepositoryMockRecorder is the mock recorder for MockCOPReadModelRepository.
type MockCOPReadModelRepositoryMockRecorder struct {
	mock *MockCOPReadModelRepository
}

// NewMockCOPReadModelRepository creates a new mock instance.
func NewMockCOPReadModelRepository(ctrl *gomock.Controller) *MockCOPReadModelRepository {
	mock := &MockCOPReadModelRepository{ctrl: ctrl}
	mock.recorder = &MockCOPReadModelRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCOPReadModelRepository) EXPECT() *MockCOPReadModelRepositoryMockRecorder {
	return m.recorder
}

// LoadCOPReadModel mocks base method.
func (m *MockCOPReadModelRepository) LoadCOPReadModel(ctx context.Context) (contracts.ProjectionResult, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadCOPReadModel", ctx)
	ret0, _ := ret[0].(contracts.ProjectionResult)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// LoadCOPReadModel indicates an expected call of LoadCOPReadModel.
func (mr *MockCOPReadModelRepositoryMockRecorder) LoadCOPReadModel(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadCOPReadModel", reflect.TypeOf((*MockCOPReadModelRepository)(nil).LoadCOPReadModel), ctx)
}

// SaveCOPReadModel mocks base method.
func (m *MockCOPReadModelRepository) SaveCOPReadModel(ctx context.Context, result contracts.ProjectionResult) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveCOPReadModel", ctx, result)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveCOPReadModel indicates an expected call of SaveCOPReadModel.
func (mr *MockCOPReadModelRepositoryMockRecorder) SaveCOPReadModel(ctx, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCOPReadModel", reflect.TypeOf((*MockCOPReadModelRepository)(nil).SaveCOPReadModel), ctx, result)
}

// MockProjectorDispatcher is a mock of ProjectorDispatcher interface.
type MockProjectorDispatcher struct {
	ctrl     *gomock.Controller
	recorder *MockProjectorDispatcherMockRecorder
	isgomock struct{}
}

// MockProjectorDispatcherMockRecorder is the mock recorder for MockProjectorDispatcher.
type MockProjectorDispatcherMockRecorder struct {
	mock *MockProjectorDispatcher
}

// NewMockProjectorDispatcher creates a new mock instance.
func NewMockProjectorDispatcher(ctrl *gomock.Controller) *MockProjectorDispatcher {
	mock := &MockProjectorDispatcher{ctrl: ctrl}
	mock.recorder = &MockProjectorDispatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectorDispatcher) EXPECT() *MockProjectorDispatcherMockRecorder {
	return m.recorder
}

// DispatchCanonicalEvent mocks base method.
func (m *MockProjectorDispatcher) DispatchCanonicalEvent(ctx context.Context, canonicalEventID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DispatchCanonicalEvent", ctx, canonicalEventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DispatchCanonicalEvent indicates an expected call of DispatchCanonicalEvent.
func (mr *MockProjectorDispatcherMockRecorder) DispatchCanonicalEvent(ctx, canonicalEventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DispatchCanonicalEvent", reflect.TypeOf((*MockProjectorDispatcher)(nil).DispatchCanonicalEvent), ctx, canonicalEventID)
}

// MockLunaAdapter is a mock of LunaAdapter interface.
type MockLunaAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockLunaAdapterMockRecorder
	isgomock struct{}
}

// MockLunaAdapterMockRecorder is the mock recorder for MockLunaAdapter.
type MockLunaAdapterMockRecorder struct {
	mock *MockLunaAdapter
}

// NewMockLunaAdapter creates a new mock instance.
func NewMockLunaAdapter(ctrl *gomock.Controller) *MockLunaAdapter {
	mock := &MockLunaAdapter{ctrl: ctrl}
	mock.recorder = &MockLunaAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLunaAdapter) EXPECT() *MockLunaAdapterMockRecorder {
	return m.recorder
}

// Normalize mocks base method.
func (m *MockLunaAdapter) Normalize(arg0 context.Context, arg1 gen.RawEvent) (contracts.LunaOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Normalize", arg0, arg1)
	ret0, _ := ret[0].(contracts.LunaOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Normalize indicates an expected call of Normalize.
func (mr *MockLunaAdapterMockRecorder) Normalize(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Normalize", reflect.TypeOf((*MockLunaAdapter)(nil).Normalize), arg0, arg1)
}

// MockTerraAdapter is a mock of TerraAdapter interface.
type MockTerraAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockTerraAdapterMockRecorder
	isgomock struct{}
}

// MockTerraAdapterMockRecorder is the mock recorder for MockTerraAdapter.
type MockTerraAdapterMockRecorder struct {
	mock *MockTerraAdapter
}

// NewMockTerraAdapter creates a new mock instance.
func NewMockTerraAdapter(ctrl *gomock.Controller) *MockTerraAdapter {
	mock := &MockTerraAdapter{ctrl: ctrl}
	mock.recorder = &MockTerraAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTerraAdapter) EXPECT() *MockTerraAdapterMockRecorder {
	return m.recorder
}

// Assess mocks base method.
func (m *MockTerraAdapter) Assess(arg0 context.Context, arg1 contracts.TerraInput) (contracts.TerraOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Assess", arg0, arg1)
	ret0, _ := ret[0].(contracts.TerraOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Assess indicates an expected call of Assess.
func (mr *MockTerraAdapterMockRecorder) Assess(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Assess", reflect.TypeOf((*MockTerraAdapter)(nil).Assess), arg0, arg1)
}

// MockSolAdapter is a mock of SolAdapter interface.
type MockSolAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockSolAdapterMockRecorder
	isgomock struct{}
}

// MockSolAdapterMockRecorder is the mock recorder for MockSolAdapter.
type MockSolAdapterMockRecorder struct {
	mock *MockSolAdapter
}

// NewMockSolAdapter creates a new mock instance.
func NewMockSolAdapter(ctrl *gomock.Controller) *MockSolAdapter {
	mock := &MockSolAdapter{ctrl: ctrl}
	mock.recorder = &MockSolAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSolAdapter) EXPECT() *MockSolAdapterMockRecorder {
	return m.recorder
}

// Brief mocks base method.
func (m *MockSolAdapter) Brief(arg0 context.Context, arg1 contracts.SolInput) (contracts.SolOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Brief", arg0, arg1)
	ret0, _ := ret[0].(contracts.SolOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Brief indicates an expected call of Brief.
func (mr *MockSolAdapterMockRecorder) Brief(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Brief", reflect.TypeOf((*MockSolAdapter)(nil).Brief), arg0, arg1)
}

// MockSimulationSchedule is a mock of SimulationSchedule interface.
type MockSimulationSchedule struct {
	ctrl     *gomock.Controller
	recorder *MockSimulationScheduleMockRecorder
	isgomock struct{}
}

// MockSimulationScheduleMockRecorder is the mock recorder for MockSimulationSchedule.
type MockSimulationScheduleMockRecorder struct {
	mock *MockSimulationSchedule
}

// NewMockSimulationSchedule creates a new mock instance.
func NewMockSimulationSchedule(ctrl *gomock.Controller) *MockSimulationSchedule {
	mock := &MockSimulationSchedule{ctrl: ctrl}
	mock.recorder = &MockSimulationScheduleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSimulationSchedule) EXPECT() *MockSimulationScheduleMockRecorder {
	return m.recorder
}

// Beats mocks base method.
func (m *MockSimulationSchedule) Beats() []contracts.ScheduledBeat {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Beats")
	ret0, _ := ret[0].([]contracts.ScheduledBeat)
	return ret0
}

// Beats indicates an expected call of Beats.
func (mr *MockSimulationScheduleMockRecorder) Beats() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Beats", reflect.TypeOf((*MockSimulationSchedule)(nil).Beats))
}

// MockSimulationStreamSubscription is a mock of SimulationStreamSubscription interface.
type MockSimulationStreamSubscription struct {
	ctrl     *gomock.Controller
	recorder *MockSimulationStreamSubscriptionMockRecorder
	isgomock struct{}
}

// MockSimulationStreamSubscriptionMockRecorder is the mock recorder for MockSimulationStreamSubscription.
type MockSimulationStreamSubscriptionMockRecorder struct {
	mock *MockSimulationStreamSubscription
}

// NewMockSimulationStreamSubscription creates a new mock instance.
func NewMockSimulationStreamSubscription(ctrl *gomock.Controller) *MockSimulationStreamSubscription {
	mock := &MockSimulationStreamSubscription{ctrl: ctrl}
	mock.recorder = &MockSimulationStreamSubscriptionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSimulationStreamSubscription) EXPECT() *MockSimulationStreamSubscriptionMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockSimulationStreamSubscription) Cancel() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Cancel")
}

// Cancel indicates an expected call of Cancel.
func (mr *MockSimulationStreamSubscriptionMockRecorder) Cancel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockSimulationStreamSubscription)(nil).Cancel))
}

// Events mocks base method.
func (m *MockSimulationStreamSubscription) Events() <-chan contracts.SimulationStreamEvent {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Events")
	ret0, _ := ret[0].(<-chan contracts.SimulationStreamEvent)
	return ret0
}

// Events indicates an expected call of Events.
func (mr *MockSimulationStreamSubscriptionMockRecorder) Events() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Events", reflect.TypeOf((*MockSimulationStreamSubscription)(nil).Events))
}
