// Command schema-gen generates checked-in Go record types from authored schemas
// and checks the schema/fixture contract gate.
package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"go/format"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"mosaic.local/mosaic/internal/ontology"
)

const generatedPath = "internal/ontology/gen/types_gen.go"

func main() {
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, "schema-gen:", err)
		os.Exit(1)
	}
}

func run(args []string) error {
	mode := "check"
	if len(args) > 1 {
		return errors.New("usage: schema-gen [check|generate]")
	}
	if len(args) == 1 {
		mode = args[0]
	}
	if mode != "check" && mode != "generate" {
		return errors.New("usage: schema-gen [check|generate]")
	}
	root, err := findModuleRoot()
	if err != nil {
		return err
	}
	schemas, err := ontology.CompileDir(filepath.Join(root, "ontology"))
	if err != nil {
		return err
	}
	if err := ontology.ValidateFixtureDir(schemas, filepath.Join(root, "internal", "ontology", "testdata", "fixtures")); err != nil {
		return err
	}
	generated, err := render(root)
	if err != nil {
		return err
	}
	path := filepath.Join(root, generatedPath)
	if mode == "generate" {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return fmt.Errorf("create generated directory: %w", err)
		}
		if err := os.WriteFile(path, generated, 0o644); err != nil {
			return fmt.Errorf("write generated code: %w", err)
		}
		return nil
	}
	actual, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read generated code: %w (run: go run ./cmd/schema-gen generate)", err)
	}
	if !bytes.Equal(actual, generated) {
		return fmt.Errorf("generated code is stale (run: go run ./cmd/schema-gen generate)")
	}
	return nil
}

type authoredSchema struct {
	ID         string                     `json:"$id"`
	Title      string                     `json:"title"`
	Properties map[string]json.RawMessage `json:"properties"`
}

type field struct {
	JSON string
	Go   string
	Type string
}

type record struct {
	ID      string
	Title   string
	Version string
	Fields  []field
}

func render(root string) ([]byte, error) {
	records := make([]record, 0, len(ontology.SchemaFiles))
	for _, file := range ontology.SchemaFiles {
		content, err := os.ReadFile(filepath.Join(root, "ontology", file))
		if err != nil {
			return nil, fmt.Errorf("read %s: %w", file, err)
		}
		var schema authoredSchema
		if err := json.Unmarshal(content, &schema); err != nil {
			return nil, fmt.Errorf("decode %s: %w", file, err)
		}
		version, err := versionFromProperties(schema.Properties)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", file, err)
		}
		fields := make([]field, 0, len(schema.Properties))
		for name, value := range schema.Properties {
			fields = append(fields, field{JSON: name, Go: goName(name), Type: goType(value)})
		}
		sort.Slice(fields, func(i, j int) bool { return fields[i].JSON < fields[j].JSON })
		records = append(records, record{ID: schema.ID, Title: schema.Title, Version: version, Fields: fields})
	}

	var out strings.Builder
	out.WriteString("// Code generated by cmd/schema-gen; DO NOT EDIT.\n\n")
	out.WriteString("// Package gen contains record shells generated from ontology/*.schema.json.\n")
	out.WriteString("package gen\n\n")
	out.WriteString("import \"encoding/json\"\n\n")
	out.WriteString("// SchemaMeta identifies an immutable authored JSON Schema version.\n")
	out.WriteString("type SchemaMeta struct {\n\tID string\n\tVersion string\n}\n\n")
	out.WriteString("// SchemaMetadata is keyed by authored schema filename.\n")
	out.WriteString("var SchemaMetadata = map[string]SchemaMeta{\n")
	for i, item := range records {
		fmt.Fprintf(&out, "\t%q: {ID: %q, Version: %q},\n", ontology.SchemaFiles[i], item.ID, item.Version)
	}
	out.WriteString("}\n\n")
	for _, item := range records {
		fmt.Fprintf(&out, "// %s is generated from the immutable %s contract.\n", item.Title, item.ID)
		fmt.Fprintf(&out, "type %s struct {\n", item.Title)
		for _, field := range item.Fields {
			fmt.Fprintf(&out, "\t%s %s `json:\"%s,omitempty\"`\n", field.Go, field.Type, field.JSON)
		}
		out.WriteString("}\n\n")
	}
	formatted, err := format.Source([]byte(out.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated code: %w", err)
	}
	return formatted, nil
}

func versionFromProperties(properties map[string]json.RawMessage) (string, error) {
	raw, ok := properties["schema_version"]
	if !ok {
		return "", errors.New("schema_version property missing")
	}
	var property struct {
		Const string `json:"const"`
	}
	if err := json.Unmarshal(raw, &property); err != nil {
		return "", fmt.Errorf("decode schema_version: %w", err)
	}
	if property.Const == "" {
		return "", errors.New("schema_version const missing")
	}
	return property.Const, nil
}

func goType(raw json.RawMessage) string {
	var property struct {
		Type  string `json:"type"`
		Const any    `json:"const"`
		Enum  []any  `json:"enum"`
	}
	if json.Unmarshal(raw, &property) != nil {
		return "json.RawMessage"
	}
	switch property.Type {
	case "string":
		return "string"
	case "integer":
		return "int64"
	case "number":
		return "float64"
	case "boolean":
		return "bool"
	case "object":
		return "map[string]any"
	case "array":
		return "[]any"
	}
	if property.Const != nil || len(property.Enum) > 0 {
		return "string"
	}
	return "json.RawMessage"
}

func goName(value string) string {
	initialisms := map[string]string{"id": "ID", "url": "URL", "api": "API", "cop": "COP"}
	var out strings.Builder
	for _, word := range strings.Split(value, "_") {
		if initialism, ok := initialisms[word]; ok {
			out.WriteString(initialism)
			continue
		}
		if word == "" {
			continue
		}
		out.WriteString(strings.ToUpper(word[:1]))
		out.WriteString(word[1:])
	}
	return out.String()
}

func findModuleRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", fmt.Errorf("get working directory: %w", err)
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		} else if !errors.Is(err, fs.ErrNotExist) {
			return "", fmt.Errorf("inspect module root: %w", err)
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", errors.New("could not find go.mod")
		}
		dir = parent
	}
}
