// Package datasetgen produces and promotes offline synthetic dataset candidates.
// It is intentionally separate from the Mosaic runtime.
package datasetgen

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"time"

	"mosaic.local/mosaic/internal/dataset"
	"mosaic.local/mosaic/internal/ontology"
)

const (
	// DefaultModelPath is deliberately repository-local and gitignored. It is
	// not a runtime dependency or a Docker image input.
	DefaultModelPath  = "localmodels/gemma-4-E2B-it-UD-Q8_K_XL.gguf"
	DefaultPromptPath = "prompts/datasetgen/v1.md"

	StageArtifactsDirectory = "artifacts"
	StageProvenanceFile     = "provenance.json"
	StageModelOutputFile    = "model-output.json"

	provenanceVersion     = "1.0.0"
	bundleVersion         = "1.0.0"
	maxPromptFileBytes    = 64 * 1024
	maxPromptInputBytes   = 256 * 1024
	maxModelResponseBytes = 4 * 1024 * 1024
	llamaContextTokens    = "8192"
	llamaPredictionTokens = "16384"
	llamaTemperature      = "0.2"
)

var (
	scenarioIDPattern       = regexp.MustCompile(`^[a-z0-9][a-z0-9-]{0,63}$`)
	versionedDatasetPattern = regexp.MustCompile(`^[a-z0-9][a-z0-9-]*-v[1-9][0-9]*$`)
	hexSHA256Pattern        = regexp.MustCompile(`^[a-f0-9]{64}$`)
	promptVersionPattern    = regexp.MustCompile(`^[0-9]+\.[0-9]+\.[0-9]+$`)
)

// CommandRunner is deliberately narrow so local generation tests can use a
// fake runner. Production uses ExecRunner for the offline provider.
type CommandRunner interface {
	Run(ctx context.Context, executable string, args []string) ([]byte, error)
}

// ExecRunner invokes the explicitly supplied local llama.cpp executable.
type ExecRunner struct{}

// Run executes one local command and returns its stdout. Stderr is attached to
// the returned error by os/exec when the command fails.
func (ExecRunner) Run(ctx context.Context, executable string, args []string) ([]byte, error) {
	return exec.CommandContext(ctx, executable, args...).Output()
}

// GenerateConfig describes an offline candidate-generation run.
type GenerateConfig struct {
	LlamaPath  string
	ModelPath  string
	PromptPath string
	StageDir   string
	ScenarioID string
	Seed       int64

	Runner CommandRunner
	Now    func() time.Time
}

// FileIdentity makes an input auditable without copying a model binary into the
// repository or a frozen dataset.
type FileIdentity struct {
	Path   string `json:"path"`
	SHA256 string `json:"sha256"`
	Size   int64  `json:"size_bytes"`
}

// PromptIdentity names the version marker embedded in a versioned prompt file.
type PromptIdentity struct {
	Path    string `json:"path"`
	SHA256  string `json:"sha256"`
	Size    int64  `json:"size_bytes"`
	Version string `json:"version"`
}

// Provenance is stored beside staged candidates. It records the process, not a
// claim that an LLM response can be regenerated byte-for-byte.
type Provenance struct {
	Version           string               `json:"version"`
	GeneratedAt       string               `json:"generated_at"`
	Model             *FileIdentity        `json:"model,omitempty"`
	LlamaExecutable   *FileIdentity        `json:"llama_executable,omitempty"`
	RemoteModel       *RemoteModelIdentity `json:"remote_model,omitempty"`
	Prompt            PromptIdentity       `json:"prompt"`
	ScenarioID        string               `json:"scenario_id"`
	Seed              int64                `json:"seed"`
	CommandArgs       []string             `json:"command_args,omitempty"`
	RequestParameters []string             `json:"request_parameters,omitempty"`
	PromptInputSHA256 string               `json:"prompt_input_sha256"`
	RawResponseSHA256 string               `json:"raw_response_sha256"`
	SchemaVersions    map[string]string    `json:"schema_versions"`
}

// FreezeConfig promotes a reviewed stage into a new versioned frozen dataset.
type FreezeConfig struct {
	InputDir  string
	OutputDir string
}

type artifactBundle struct {
	BundleVersion string        `json:"bundle_version"`
	ScenarioID    string        `json:"scenario_id"`
	Artifacts     artifactFiles `json:"artifacts"`
}

type artifactFiles struct {
	Manifest         json.RawMessage `json:"manifest.json"`
	Scenario         json.RawMessage `json:"scenario.json"`
	RawEvents        json.RawMessage `json:"raw-events.json"`
	ExpectedOutcomes json.RawMessage `json:"expected-outcomes.json"`
}

func (files artifactFiles) named() []namedArtifact {
	return []namedArtifact{
		{Name: "manifest.json", Content: files.Manifest},
		{Name: "scenario.json", Content: files.Scenario},
		{Name: "raw-events.json", Content: files.RawEvents},
		{Name: "expected-outcomes.json", Content: files.ExpectedOutcomes},
	}
}

type namedArtifact struct {
	Name    string
	Content []byte
}

// Generate invokes the supplied local llama.cpp executable once and writes the
// parsed candidate bundle and its provenance under StageDir. It never validates
// a candidate as frozen data and never writes to datasets/.
func Generate(root string, config GenerateConfig) (Provenance, error) {
	if err := validateScenarioID(config.ScenarioID); err != nil {
		return Provenance{}, err
	}
	if config.Runner == nil {
		return Provenance{}, errors.New("generate: command runner is required")
	}
	if config.LlamaPath == "" {
		return Provenance{}, errors.New("generate: --llama is required")
	}
	if config.ModelPath == "" {
		config.ModelPath = DefaultModelPath
	}
	if config.PromptPath == "" {
		config.PromptPath = DefaultPromptPath
	}
	if config.StageDir == "" {
		return Provenance{}, errors.New("generate: --stage is required")
	}
	if config.Now == nil {
		config.Now = time.Now
	}

	root, err := absolutePath(root)
	if err != nil {
		return Provenance{}, fmt.Errorf("generate: resolve repository root: %w", err)
	}
	llamaPath, err := resolvePath(root, config.LlamaPath)
	if err != nil {
		return Provenance{}, fmt.Errorf("generate: resolve llama executable: %w", err)
	}
	modelPath, err := resolvePath(root, config.ModelPath)
	if err != nil {
		return Provenance{}, fmt.Errorf("generate: resolve model: %w", err)
	}
	promptPath, err := resolvePath(root, config.PromptPath)
	if err != nil {
		return Provenance{}, fmt.Errorf("generate: resolve prompt: %w", err)
	}
	stageDir, err := resolvePath(root, config.StageDir)
	if err != nil {
		return Provenance{}, fmt.Errorf("generate: resolve staging directory: %w", err)
	}

	llamaIdentity, err := identifyFile(llamaPath)
	if err != nil {
		return Provenance{}, fmt.Errorf("generate: llama executable: %w", err)
	}
	modelIdentity, err := identifyFile(modelPath)
	if err != nil {
		return Provenance{}, fmt.Errorf("generate: local model: %w", err)
	}
	promptContent, promptIdentity, err := readPrompt(promptPath)
	if err != nil {
		return Provenance{}, fmt.Errorf("generate: prompt: %w", err)
	}
	schemas, schemaVersions, err := compileSchemas(root)
	if err != nil {
		return Provenance{}, fmt.Errorf("generate: compile schemas: %w", err)
	}
	_ = schemas // compilation is both a gate and the source of recorded versions.
	promptInput, err := boundedPromptInput(root, promptContent, config.ScenarioID)
	if err != nil {
		return Provenance{}, fmt.Errorf("generate: build bounded prompt: %w", err)
	}
	if err := prepareEmptyStage(stageDir); err != nil {
		return Provenance{}, fmt.Errorf("generate: staging directory: %w", err)
	}

	args := llamaArguments(modelPath, config.Seed, string(promptInput))
	response, err := config.Runner.Run(context.Background(), llamaPath, args)
	if err != nil {
		return Provenance{}, fmt.Errorf("generate: run local llama.cpp: %w", err)
	}
	if len(response) > maxModelResponseBytes {
		return Provenance{}, fmt.Errorf("generate: model response is %d bytes; limit is %d", len(response), maxModelResponseBytes)
	}
	response, err = extractJSONObject(response)
	if err != nil {
		return Provenance{}, fmt.Errorf("generate: model output: %w", err)
	}
	bundle, err := parseArtifactBundle(response)
	if err != nil {
		return Provenance{}, fmt.Errorf("generate: model output: %w", err)
	}
	if bundle.ScenarioID != config.ScenarioID {
		return Provenance{}, fmt.Errorf("generate: model output scenario_id %q does not match requested %q", bundle.ScenarioID, config.ScenarioID)
	}
	if err := bundle.validateScenarioArtifact(); err != nil {
		return Provenance{}, fmt.Errorf("generate: model output: %w", err)
	}

	rawResponseHash := sha256Hex(response)
	promptInputHash := sha256Hex(promptInput)
	provenance := Provenance{
		Version:           provenanceVersion,
		GeneratedAt:       config.Now().UTC().Format(time.RFC3339Nano),
		Model:             &modelIdentity,
		LlamaExecutable:   &llamaIdentity,
		Prompt:            promptIdentity,
		ScenarioID:        config.ScenarioID,
		Seed:              config.Seed,
		CommandArgs:       recordedArguments(args),
		PromptInputSHA256: promptInputHash,
		RawResponseSHA256: rawResponseHash,
		SchemaVersions:    schemaVersions,
	}
	if err := writeStage(stageDir, response, bundle, provenance); err != nil {
		return Provenance{}, fmt.Errorf("generate: write staged candidate: %w", err)
	}
	return provenance, nil
}

// Freeze validates a complete staged candidate and atomically promotes only its
// four frozen artifacts. The staging directory is never changed, including on
// validation or destination failures.
func Freeze(root string, config FreezeConfig) error {
	if config.InputDir == "" || config.OutputDir == "" {
		return errors.New("freeze: --input and --output are required")
	}
	root, err := absolutePath(root)
	if err != nil {
		return fmt.Errorf("freeze: resolve repository root: %w", err)
	}
	inputDir, err := resolvePath(root, config.InputDir)
	if err != nil {
		return fmt.Errorf("freeze: resolve input: %w", err)
	}
	outputDir, err := resolvePath(root, config.OutputDir)
	if err != nil {
		return fmt.Errorf("freeze: resolve output: %w", err)
	}
	if err := validateFreezeDestination(root, outputDir); err != nil {
		return fmt.Errorf("freeze: output: %w", err)
	}

	stage, err := validateStagedCandidate(root, inputDir)
	if err != nil {
		return fmt.Errorf("freeze: staged candidate: %w", err)
	}

	datasetsRoot := filepath.Join(root, "datasets")
	temporaryDir, err := os.MkdirTemp(datasetsRoot, ".datasetgen-freeze-")
	if err != nil {
		return fmt.Errorf("freeze: create temporary dataset directory: %w", err)
	}
	removeTemporary := true
	defer func() {
		if removeTemporary {
			_ = os.RemoveAll(temporaryDir)
		}
	}()
	for _, artifact := range stage.Artifacts.named() {
		if err := os.WriteFile(filepath.Join(temporaryDir, artifact.Name), artifact.Content, 0o644); err != nil {
			return fmt.Errorf("freeze: write %s: %w", artifact.Name, err)
		}
	}
	if err := os.Rename(temporaryDir, outputDir); err != nil {
		return fmt.Errorf("freeze: promote candidate: %w", err)
	}
	removeTemporary = false
	return nil
}

// ValidateStage performs every non-mutating validation required before a
// reviewed candidate may be frozen. It never creates, modifies, or removes a
// staged artifact or frozen dataset.
func ValidateStage(root, inputDir string) error {
	if inputDir == "" {
		return errors.New("validate stage: --input is required")
	}
	root, err := absolutePath(root)
	if err != nil {
		return fmt.Errorf("validate stage: resolve repository root: %w", err)
	}
	inputDir, err = resolvePath(root, inputDir)
	if err != nil {
		return fmt.Errorf("validate stage: resolve input: %w", err)
	}
	if _, err := validateStagedCandidate(root, inputDir); err != nil {
		return fmt.Errorf("validate stage: %w", err)
	}
	return nil
}

func validateStagedCandidate(root, inputDir string) (stagedCandidate, error) {
	schemas, versions, err := compileSchemas(root)
	if err != nil {
		return stagedCandidate{}, fmt.Errorf("compile schemas: %w", err)
	}
	stage, err := readStage(inputDir)
	if err != nil {
		return stagedCandidate{}, err
	}
	if err := validateProvenance(stage.Provenance, versions); err != nil {
		return stagedCandidate{}, fmt.Errorf("provenance: %w", err)
	}
	if sha256Hex(stage.ModelOutput) != stage.Provenance.RawResponseSHA256 {
		return stagedCandidate{}, errors.New("model-output checksum does not match provenance")
	}
	bundle, err := parseArtifactBundle(stage.ModelOutput)
	if err != nil {
		return stagedCandidate{}, fmt.Errorf("model-output: %w", err)
	}
	if bundle.ScenarioID != stage.Provenance.ScenarioID {
		return stagedCandidate{}, errors.New("provenance scenario does not match model output")
	}
	if err := bundle.validateScenarioArtifact(); err != nil {
		return stagedCandidate{}, fmt.Errorf("model-output: %w", err)
	}
	if err := stage.matchesBundle(bundle); err != nil {
		return stagedCandidate{}, fmt.Errorf("staged artifacts: %w", err)
	}
	if err := dataset.ValidateArtifacts(schemas, filepath.Join(inputDir, StageArtifactsDirectory)); err != nil {
		return stagedCandidate{}, fmt.Errorf("validate candidate artifacts: %w", err)
	}
	return stage, nil
}

type stagedCandidate struct {
	Directory   string
	ModelOutput []byte
	Provenance  Provenance
	Artifacts   artifactFiles
}

func readStage(dir string) (stagedCandidate, error) {
	if err := validateStageDirectory(dir); err != nil {
		return stagedCandidate{}, err
	}
	modelOutput, err := os.ReadFile(filepath.Join(dir, StageModelOutputFile))
	if err != nil {
		return stagedCandidate{}, fmt.Errorf("read model output: %w", err)
	}
	var provenance Provenance
	if err := readStrictJSON(filepath.Join(dir, StageProvenanceFile), &provenance); err != nil {
		return stagedCandidate{}, fmt.Errorf("read provenance: %w", err)
	}
	bundle, err := parseArtifactBundle(modelOutput)
	if err != nil {
		return stagedCandidate{}, fmt.Errorf("parse model output: %w", err)
	}
	return stagedCandidate{Directory: dir, ModelOutput: modelOutput, Provenance: provenance, Artifacts: bundle.Artifacts}, nil
}

func (stage stagedCandidate) matchesBundle(bundle artifactBundle) error {
	for _, artifact := range bundle.Artifacts.named() {
		content, err := os.ReadFile(filepath.Join(stage.Directory, StageArtifactsDirectory, artifact.Name))
		if err != nil {
			return err
		}
		if !bytes.Equal(content, artifact.Content) {
			return fmt.Errorf("%s differs from model-output.json", artifact.Name)
		}
	}
	return nil
}

func writeStage(dir string, response []byte, bundle artifactBundle, provenance Provenance) error {
	artifactsDir := filepath.Join(dir, StageArtifactsDirectory)
	if err := os.Mkdir(artifactsDir, 0o755); err != nil {
		return err
	}
	for _, artifact := range bundle.Artifacts.named() {
		if err := os.WriteFile(filepath.Join(artifactsDir, artifact.Name), artifact.Content, 0o644); err != nil {
			return fmt.Errorf("write %s: %w", artifact.Name, err)
		}
	}
	if err := os.WriteFile(filepath.Join(dir, StageModelOutputFile), response, 0o644); err != nil {
		return err
	}
	encoded, err := json.MarshalIndent(provenance, "", "  ")
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(dir, StageProvenanceFile), append(encoded, '\n'), 0o644); err != nil {
		return err
	}
	return nil
}

func extractJSONObject(output []byte) ([]byte, error) {
	start := bytes.IndexByte(output, '{')
	end := bytes.LastIndexByte(output, '}')
	if start < 0 || end < start {
		return nil, errors.New("no JSON object in model output")
	}
	return bytes.TrimSpace(output[start : end+1]), nil
}
func parseArtifactBundle(content []byte) (artifactBundle, error) {
	if len(content) == 0 {
		return artifactBundle{}, errors.New("response is empty")
	}
	var bundle artifactBundle
	decoder := json.NewDecoder(bytes.NewReader(content))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&bundle); err != nil {
		return artifactBundle{}, err
	}
	var extra any
	if err := decoder.Decode(&extra); err != io.EOF {
		return artifactBundle{}, errors.New("response must contain exactly one JSON object")
	}
	if bundle.BundleVersion != bundleVersion {
		return artifactBundle{}, fmt.Errorf("bundle_version must be %q", bundleVersion)
	}
	if err := validateScenarioID(bundle.ScenarioID); err != nil {
		return artifactBundle{}, fmt.Errorf("bundle scenario_id: %w", err)
	}
	for _, artifact := range bundle.Artifacts.named() {
		if len(artifact.Content) == 0 {
			return artifactBundle{}, fmt.Errorf("%s is required", artifact.Name)
		}
		var object map[string]any
		decoder := json.NewDecoder(bytes.NewReader(artifact.Content))
		decoder.DisallowUnknownFields()
		if err := decoder.Decode(&object); err != nil {
			return artifactBundle{}, fmt.Errorf("%s must be a JSON object: %w", artifact.Name, err)
		}
		if object == nil {
			return artifactBundle{}, fmt.Errorf("%s must be a JSON object", artifact.Name)
		}
		if err := decoder.Decode(&extra); err != io.EOF {
			return artifactBundle{}, fmt.Errorf("%s must contain exactly one JSON value", artifact.Name)
		}
	}
	return bundle, nil
}

func (bundle artifactBundle) validateScenarioArtifact() error {
	var scenario struct {
		ScenarioID string `json:"scenario_id"`
	}
	if err := json.Unmarshal(bundle.Artifacts.Scenario, &scenario); err != nil {
		return fmt.Errorf("scenario.json: %w", err)
	}
	if err := validateScenarioID(scenario.ScenarioID); err != nil {
		return fmt.Errorf("scenario.json scenario_id: %w", err)
	}
	return nil
}

func compileSchemas(root string) (map[string]ontology.Schema, map[string]string, error) {
	schemas, err := ontology.CompileDir(filepath.Join(root, "ontology"))
	if err != nil {
		return nil, nil, err
	}
	versions := make(map[string]string, len(ontology.SchemaFiles))
	for _, name := range ontology.SchemaFiles {
		versions[name] = schemas[name].Version
	}
	return schemas, versions, nil
}

func readPrompt(path string) ([]byte, PromptIdentity, error) {
	content, err := os.ReadFile(path)
	if err != nil {
		return nil, PromptIdentity{}, err
	}
	if len(content) == 0 || len(content) > maxPromptFileBytes {
		return nil, PromptIdentity{}, fmt.Errorf("must be between 1 and %d bytes", maxPromptFileBytes)
	}
	version, err := promptVersion(content)
	if err != nil {
		return nil, PromptIdentity{}, err
	}
	identity, err := identifyFile(path)
	if err != nil {
		return nil, PromptIdentity{}, err
	}
	return content, PromptIdentity{Path: identity.Path, SHA256: identity.SHA256, Size: identity.Size, Version: version}, nil
}

func promptVersion(content []byte) (string, error) {
	for _, line := range strings.Split(string(content), "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "<!-- mosaic-prompt-version:") && strings.HasSuffix(line, "-->") {
			version := strings.TrimSpace(strings.TrimSuffix(strings.TrimPrefix(line, "<!-- mosaic-prompt-version:"), "-->"))
			if promptVersionPattern.MatchString(version) {
				return version, nil
			}
			return "", fmt.Errorf("version %q is not semantic major.minor.patch", version)
		}
	}
	return "", errors.New("missing <!-- mosaic-prompt-version: major.minor.patch --> marker")
}

func boundedPromptInput(root string, prompt []byte, scenarioID string) ([]byte, error) {
	var builder strings.Builder
	builder.Write(prompt)
	builder.WriteString("\n\n## Bounded generation request\n")
	builder.WriteString("scenario_id: ")
	builder.WriteString(scenarioID)
	builder.WriteString("\n\n## Read-only Mosaic schemas\n")
	for _, name := range ontology.SchemaFiles {
		content, err := os.ReadFile(filepath.Join(root, "ontology", name))
		if err != nil {
			return nil, fmt.Errorf("read %s: %w", name, err)
		}
		builder.WriteString("\n### ")
		builder.WriteString(name)
		builder.WriteString("\n")
		builder.Write(content)
		builder.WriteString("\n")
		if builder.Len() > maxPromptInputBytes {
			return nil, fmt.Errorf("prompt plus schemas exceeds %d bytes", maxPromptInputBytes)
		}
	}
	return []byte(builder.String()), nil
}

func llamaArguments(modelPath string, seed int64, prompt string) []string {
	return []string{
		"-m", modelPath,
		"--seed", strconv.FormatInt(seed, 10),
		"--temp", llamaTemperature,
		"--ctx-size", llamaContextTokens,
		"--n-predict", llamaPredictionTokens,
		"--no-display-prompt",
		"--simple-io",
		"--single-turn",
		"-p", prompt,
	}
}

func recordedArguments(args []string) []string {
	recorded := append([]string(nil), args...)
	for index, argument := range recorded {
		if (argument == "-p" || argument == "--prompt") && index+1 < len(recorded) {
			recorded[index+1] = "sha256:" + sha256Hex([]byte(recorded[index+1]))
		}
		if (argument == "--token" || argument == "--api-key" || argument == "--password") && index+1 < len(recorded) {
			recorded[index+1] = "[redacted]"
		}
	}
	return recorded
}

func validateStageDirectory(dir string) error {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return err
	}
	expected := map[string]bool{
		StageArtifactsDirectory: true,
		StageModelOutputFile:    true,
		StageProvenanceFile:     true,
	}
	for _, entry := range entries {
		if !expected[entry.Name()] || entry.Type()&fs.ModeSymlink != 0 {
			return fmt.Errorf("unexpected staged entry %q", entry.Name())
		}
	}
	for name := range expected {
		if _, err := os.Stat(filepath.Join(dir, name)); err != nil {
			return fmt.Errorf("missing %s", name)
		}
	}
	info, err := os.Stat(filepath.Join(dir, StageArtifactsDirectory))
	if err != nil {
		return err
	}
	if !info.IsDir() {
		return errors.New("artifacts must be a directory")
	}
	artifactEntries, err := os.ReadDir(filepath.Join(dir, StageArtifactsDirectory))
	if err != nil {
		return err
	}
	allowedArtifacts := map[string]bool{"manifest.json": true, "scenario.json": true, "raw-events.json": true, "expected-outcomes.json": true}
	for _, entry := range artifactEntries {
		if !allowedArtifacts[entry.Name()] || entry.IsDir() || entry.Type()&fs.ModeSymlink != 0 {
			return fmt.Errorf("unexpected staged artifact %q", entry.Name())
		}
	}
	return nil
}

func prepareEmptyStage(dir string) error {
	info, err := os.Stat(dir)
	if err == nil {
		if !info.IsDir() {
			return errors.New("must be a directory")
		}
		entries, err := os.ReadDir(dir)
		if err != nil {
			return err
		}
		if len(entries) != 0 {
			return errors.New("must be new or empty; refusing to overwrite staged files")
		}
		return nil
	}
	if !errors.Is(err, fs.ErrNotExist) {
		return err
	}
	return os.MkdirAll(dir, 0o755)
}

func validateFreezeDestination(root, output string) error {
	datasetsRoot := filepath.Join(root, "datasets")
	datasetsInfo, err := os.Stat(datasetsRoot)
	if err != nil {
		return fmt.Errorf("datasets root: %w", err)
	}
	if !datasetsInfo.IsDir() {
		return errors.New("datasets root is not a directory")
	}
	if filepath.Base(output) == "." || filepath.Base(output) == string(filepath.Separator) || !versionedDatasetPattern.MatchString(filepath.Base(output)) {
		return errors.New("target directory must have a versioned name such as domestic-disturbance-v2")
	}
	parent, err := filepath.EvalSymlinks(filepath.Dir(output))
	if err != nil {
		return fmt.Errorf("resolve output parent: %w", err)
	}
	realDatasetsRoot, err := filepath.EvalSymlinks(datasetsRoot)
	if err != nil {
		return fmt.Errorf("resolve datasets root: %w", err)
	}
	if !samePath(parent, realDatasetsRoot) {
		return errors.New("target must be a direct child of the repository datasets directory")
	}
	if _, err := os.Lstat(output); err == nil {
		return errors.New("target already exists; refusing to overwrite a frozen dataset")
	} else if !errors.Is(err, fs.ErrNotExist) {
		return err
	}
	return nil
}

func validateProvenance(provenance Provenance, expectedVersions map[string]string) error {
	if provenance.Version != provenanceVersion && provenance.Version != remoteProvenanceVersion {
		return fmt.Errorf("version must be %q or %q", provenanceVersion, remoteProvenanceVersion)
	}
	if _, err := time.Parse(time.RFC3339Nano, provenance.GeneratedAt); err != nil {
		return fmt.Errorf("generated_at: %w", err)
	}
	if err := validateScenarioID(provenance.ScenarioID); err != nil {
		return fmt.Errorf("scenario_id: %w", err)
	}
	if provenance.RemoteModel != nil {
		if provenance.Version != remoteProvenanceVersion {
			return errors.New("remote model requires remote provenance version")
		}
		if provenance.Model != nil || provenance.LlamaExecutable != nil {
			return errors.New("remote model cannot include local file identities")
		}
		if provenance.RemoteModel.Provider != "cerebras" || provenance.RemoteModel.ModelID != CerebrasGemmaModel {
			return errors.New("remote model identity is not the approved Cerebras Gemma model")
		}
		if _, err := normalizedCerebrasEndpoint(provenance.RemoteModel.Endpoint); err != nil {
			return fmt.Errorf("remote model endpoint: %w", err)
		}
		if len(provenance.CommandArgs) != 0 || len(provenance.RequestParameters) == 0 {
			return errors.New("remote request provenance is incomplete")
		}
	} else {
		if provenance.Version != provenanceVersion {
			return errors.New("local model requires local provenance version")
		}
		for name, identity := range map[string]*FileIdentity{"model": provenance.Model, "llama_executable": provenance.LlamaExecutable} {
			if identity == nil || identity.Path == "" || identity.Size < 0 || !hexSHA256Pattern.MatchString(identity.SHA256) {
				return fmt.Errorf("%s identity is incomplete", name)
			}
		}
		if len(provenance.CommandArgs) == 0 || len(provenance.RequestParameters) != 0 {
			return errors.New("local command provenance is incomplete")
		}
	}
	if provenance.Prompt.Path == "" || provenance.Prompt.Size < 0 || !hexSHA256Pattern.MatchString(provenance.Prompt.SHA256) || !promptVersionPattern.MatchString(provenance.Prompt.Version) {
		return errors.New("prompt identity is incomplete")
	}
	if !hexSHA256Pattern.MatchString(provenance.PromptInputSHA256) || !hexSHA256Pattern.MatchString(provenance.RawResponseSHA256) {
		return errors.New("response provenance is incomplete")
	}
	if len(provenance.SchemaVersions) != len(expectedVersions) {
		return errors.New("schema_versions is incomplete")
	}
	for name, expected := range expectedVersions {
		if provenance.SchemaVersions[name] != expected {
			return fmt.Errorf("schema_versions.%s = %q, want %q", name, provenance.SchemaVersions[name], expected)
		}
	}
	return nil
}

func identifyFile(path string) (FileIdentity, error) {
	info, err := os.Stat(path)
	if err != nil {
		return FileIdentity{}, err
	}
	if !info.Mode().IsRegular() {
		return FileIdentity{}, errors.New("must be a regular file")
	}
	content, err := os.ReadFile(path)
	if err != nil {
		return FileIdentity{}, err
	}
	return FileIdentity{Path: path, SHA256: sha256Hex(content), Size: info.Size()}, nil
}

func readStrictJSON(path string, destination any) error {
	content, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	decoder := json.NewDecoder(bytes.NewReader(content))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(destination); err != nil {
		return err
	}
	var extra any
	if err := decoder.Decode(&extra); err != io.EOF {
		return errors.New("must contain exactly one JSON value")
	}
	return nil
}

func validateScenarioID(value string) error {
	if !scenarioIDPattern.MatchString(value) {
		return errors.New("scenario_id must use lowercase letters, digits, and hyphens (1-64 characters)")
	}
	return nil
}

func resolvePath(root, path string) (string, error) {
	if !filepath.IsAbs(path) {
		path = filepath.Join(root, path)
	}
	return absolutePath(path)
}

func absolutePath(path string) (string, error) {
	return filepath.Abs(filepath.Clean(path))
}

func samePath(left, right string) bool {
	left, err := absolutePath(left)
	if err != nil {
		return false
	}
	right, err = absolutePath(right)
	if err != nil {
		return false
	}
	return strings.EqualFold(left, right)
}

func sha256Hex(content []byte) string {
	sum := sha256.Sum256(content)
	return hex.EncodeToString(sum[:])
}
